#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other POSIX-compliant shell such as ksh or
#     bash, then to run this script, type that shell name before the whole
#     command line, like:
#
#         ksh Gradle
#
#     Busybox and similar reduced shells will NOT work, because this script
#     requires all of these POSIX shell features:
#       * functions;
#       * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#         «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#       * compound commands having a testable exit status, especially «case»;
#       * various built-in commands including «command», «set», and «ulimit».
#
# Important for patching:
#
# (1) Consider your target platforms when choosing a prefix for the script name.
#     The «!#» prefix makes a file executable for the POSIX sh.
#
# (2) This script targets any POSIX-compliant shell (sh, bash, ksh, zsh, etc.).
#     On Solaris, /bin/sh may be a Bourne shell without POSIX compliance.

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #( absolute
      *)    app_path=$APP_HOME$link ;; #( relative
    esac
done

# This is reliable if the path is absolute, but may not be if it's relative.
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
        ;;
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command;
# * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#   shell script including quotes and variable substitutions, so put them in
#   double quotes to make sure that they are properly word-split and modified
#   by the shell as expected.  (Quotes and backslashes in the fragments must be
#   "escaped" to prevent the shell from doing the splitting/modifying.)
# * Long-form arguments are treated as regular shell words, which means
#   there is no special treatment of spaces.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$DEFAULT_JVM_OPTS" )
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# temporary marker characters and then use 'change-delimiter-using-sed' in a
# piped tr to convert those markers to newlines.
#
# In the end we pass the result as a string to eval so that the backslashes
# are correctly interpreted.
#
# NB: If the user includes their own '--' in args[],
#     then this splitting can be incorrect; thus we use the
#     workaround of passing all args to eval below and using
#     "$@" in the actual call. See:
#     http://mywiki.wooledge.org/BashFAQ/050

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^a-zA-Z0-9/=@._-]~\\&~g; ' |
        tr '\n' ' '
    ) $@"

exec "$JAVACMD" "$@"
